language: php

matrix:
  include:
    - php: 7.1
      env:
        - DEPENDENCIES='low'
    - php: 7.4
    - php: 8.0

sudo: false

before_script:
  - composer self-update
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;


script: bin/phpunit

notifications:
  irc: "irc.freenode.org#fsi-open"
